name: pre-commit.ci autofix trigger

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches: [master]
  status:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.sha || github.run_id }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  issues: write
  checks: read
  statuses: read
  contents: read

jobs:
  trigger_from_pr:
    if: >-
      github.event_name == 'pull_request_target' &&
      (
        github.event.pull_request.user.type == 'Bot' ||
        endsWith(github.event.pull_request.user.login, '[bot]')
      )
    uses: shaypal5/pre-commit-ci-autofix-trigger/.github/workflows/reusable-autofix-trigger.yml@v1
    with:
      checkout_ref: v1.0.3
      pr_number: ${{ github.event.pull_request.number }}
    secrets:
      access_token: ${{ secrets.PRE_COMMIT_CI_AUTOFIX_TOKEN }}

  trigger_from_status:
    if: >-
      github.event_name == 'status' &&
      github.event.context == 'pre-commit.ci - pr' &&
      github.event.state == 'failure'
    uses: shaypal5/pre-commit-ci-autofix-trigger/.github/workflows/reusable-autofix-trigger.yml@v1
    with:
      checkout_ref: v1.0.3
      head_sha: ${{ github.event.sha }}
    secrets:
      access_token: ${{ secrets.PRE_COMMIT_CI_AUTOFIX_TOKEN }}
